### ISSUE TITLE
rasa_stack_quickstart weatherbot rasa_core Dockerfile pulling older version of requirements.txt for rasa_core

### ISSUE THREAD

**Issue by Haythamamin** [pradeepmvn/rasa_stack_quickstart#1]
I'm trying to install docker image included with this project (Thank you for the recommendation and awesome work!) and I ran into the issue in step 10/14:

```
Step 10/14 : RUN pip install -r requirements.txt
 ---> Running in 45902691df67
Collecting apscheduler==3.5.0 (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/19/d9/ca8322005bcd84c38e38cfaf2d5bd6fb66c14b4e977e973c6bb5ac5b98c7/APScheduler-3.5.0-py2.py3-none-any.whl (60kB)
Collecting fakeredis==0.9.0 (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/d2/51/c5398a9e5c25f6bfd2edc0f101c610e569a618e8631b410312423193ccc7/fakeredis-0.9.0-py2.py3-none-any.whl
Collecting future==0.16.0 (from -r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/00/2b/8d082ddfed935f3608cc61140df6dcbf0edea1bc3ab52fb6c29ae3e81e85/future-0.16.0.tar.gz (824kB)
Collecting graphviz==0.7.1 (from -r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/95/65/0460bcb4957e027ad31d351af170dd1759aee68c90ca598ee930ac115dd1/graphviz-0.7.1-py2.py3-none-any.whl
Collecting h5py==2.7.0 (from -r requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/11/6b/32cee6f59e7a03ab7c60bb250caff63e2d20c33ebca47cf8c28f6a2d085c/h5py-2.7.0.tar.gz (256kB)
Collecting jsonpickle==0.9.4 (from -r requirements.txt (line 7))
  Downloading https://files.pythonhosted.org/packages/cc/5e/6ecbd1d27524fcafeed4                                                                                                                     f6156f47a2a79e31e4bfa383e329e9ba93c7f3ee/jsonpickle-0.9.4.tar.gz (65kB)
Collecting keras==2.0.8 (from -r requirements.txt (line 8))
  Downloading https://files.pythonhosted.org/packages/67/3f/d117d6e48b19fb958936                                                                                                                     9f4bdbe883aa88943f8bb4a850559ea5c546fefb/Keras-2.0.8-py2.py3-none-any.whl (276kB                                                                                                                     )
Collecting numpy==1.14.0 (from -r requirements.txt (line 9))
  Downloading https://files.pythonhosted.org/packages/ee/66/7c2690141c520db08b6a                                                                                                                     6f852fa768f421b0b50683b7bbcd88ef51f33170/numpy-1.14.0.zip (4.9MB)
Collecting pandoc==1.0.0b2 (from -r requirements.txt (line 10))
  Downloading https://files.pythonhosted.org/packages/51/57/94440dbaed76f6fb73f4                                                                                                                     0756e484b8de645ad36f56d4d7100e03e443591a/pandoc-1.0.0b2.tar.gz (516kB)
Collecting redis==2.10.5 (from -r requirements.txt (line 11))
  Downloading https://files.pythonhosted.org/packages/08/c1/457428f7507e27ba7144                                                                                                                     758a7b716ea35766e6d602f4a0c16e443ab3d381/redis-2.10.5-py2.py3-none-any.whl (60kB                                                                                                                     )
Collecting six==1.11.0 (from -r requirements.txt (line 12))
  Downloading https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa                                                                                                                     78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting tensorflow==1.4.1 (from -r requirements.txt (line 13))
  Could not find a version that satisfies the requirement tensorflow==1.4.1 (fro                                                                                                                     m -r requirements.txt (line 13)) (from versions: )
No matching distribution found for tensorflow==1.4.1 (from -r requirements.txt (                                                                                                                     line 13))
ERROR: Service 'rasa-core' failed to build: The command '/bin/sh -c pip install                                                                                                                      -r requirements.txt' returned a non-zero code: 1
```
I think in HEAD repo of RASA_CORE they are using tensorflow 1.8 now, check it out https://github.com/RasaHQ/rasa_core/blob/master/requirements.txt

Thanks

**Comment by Haythamamin** [comment]
That did not work unforunatly! I even ultered the dockerfile in RAsa_core and added a step to install tensorflow before requirements.txt. Tensorflow got installed but the container crashed at the step after.

```
#Uses Latest Rasa Core.
RUN git clone -b 0.9.0a3 https://github.com/RasaHQ/rasa_core.git
WORKDIR /app/rasa_core
RUN pip install tensorflow
RUN pip install -r requirements.txt
RUN pip install -e .
```
```
Step 9/15 : WORKDIR /app/rasa_core
 ---> Using cache
 ---> af0d0494a109
Step 10/15 : RUN pip install tensorflow
 ---> Running in 599b8d1f755a
Collecting tensorflow
  Could not find a version that satisfies the requirement tensorflow (from versions: )
No matching distribution found for tensorflow
ERROR: Service 'rasa-core' failed to build: The command '/bin/sh -c pip install tensorflow' returned a non-zero code: 1
```
Maybe you need to update the requirements.txt file for it to work.

**Comment by Haythamamin** [comment]
It would be great if you share with me the Python version running in rasa_core container. I encountered other problems down the line. I believe I'm running the wrong python on that node.

```
 Rasa UI Server: http://localhost:5001
rasa-ui_1         |
rasa-ui_1         | Express server listening on port 5001
rasa-ui_1         |
rasa-ui_1         | Rasa Core Error: Error: connect ECONNREFUSED 172.18.0.2:5005
rasa-ui_1         | Using connection string from: process.env.rasacoreendpoint
rasa-ui_1         |
rasa-ui_1         |
rasa-ui_1         | Postgres DB Connected
rasa-ui_1         | Using connection string from: package.json
rasa-ui_1         | Postgres Server: null:null
rasa-ui_1         | Database:rasaui
rasa-ui_1         | Schema:public
rasa-ui_1         |
rasa-nlu_1        | 2018-07-08 21:25:30+0000 [-] "172.18.0.5" - - [08/Jul/2018:21:25:30 +0000] "GET /config HTTP/1.1" 200 669 "-" "-"
rasa-ui_1         |
rasa-ui_1         | Rasa NLU Connected
rasa-ui_1         | Using connection string from: process.env.rasanluendpoint
rasa-ui_1         | Rasa NLU Server: http://rasa-nlu:5000
rasa-ui_1         |
rasa-core_1       | Traceback (most recent call last):
rasa-core_1       |   File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
rasa-core_1       |     "__main__", mod_spec)
rasa-core_1       |   File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
rasa-core_1       |     exec(code, run_globals)
rasa-core_1       |   File "/data/rasa_server.py", line 4, in <module>
rasa-core_1       |     from rasa_core.server import RasaCoreServer
rasa-core_1       | ImportError: cannot import name 'RasaCoreServer'
weatherbot_rasa-core_1 exited with code 1
```

**Comment by pradeepmvn** [comment]
@Haythamamin did this change work for you?
Looks like there was a change to python3 image 3 days back. They must have updated it to 3.7. If you have these changes in your fork feel free to submit a PR.

**Comment by Haythamamin** [comment]
On it! Thanks for all your hard work :-)
